
[functions.fetch_shared_exercise]
enabled = true
verify_jwt = true
import_map = "./functions/fetch_shared_exercise/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/fetch_shared_exercise/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/fetch_shared_exercise/*.html" ]

[functions.download_workout]
enabled = true
verify_jwt = true
import_map = "./functions/download_workout/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/download_workout/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/download_workout/*.html" ]

[functions.download_routine]
enabled = true
verify_jwt = true
import_map = "./functions/download_routine/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/download_routine/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/download_routine/*.html" ]

[functions.generate_routine]
enabled = true
verify_jwt = true
import_map = "./functions/generate_routine/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/generate_routine/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
static_files = [ "./functions/generate_routine/systemPrompt.txt" ]
